namespace OpenGL_CS.Enums {
	public enum Capabilities : uint {
		Blend = (uint)ALL.GL_BLEND,
		Clip_Distance_0 = (uint)ALL.GL_CLIP_DISTANCE0,
		Clip_Distance_1 = (uint)ALL.GL_CLIP_DISTANCE1,
		Clip_Distance_2 = (uint)ALL.GL_CLIP_DISTANCE2,
		Clip_Distance_3 = (uint)ALL.GL_CLIP_DISTANCE3,
		Clip_Distance_4 = (uint)ALL.GL_CLIP_DISTANCE4,
		Clip_Distance_5 = (uint)ALL.GL_CLIP_DISTANCE5,
		Clip_Distance_6 = (uint)ALL.GL_CLIP_DISTANCE6,
		Clip_Distance_7 = (uint)ALL.GL_CLIP_DISTANCE7,
		Cull_Face = (uint)ALL.GL_CULL_FACE,
		Debug_Output = (uint)ALL.GL_DEBUG_OUTPUT,
		Debug_Output_Synchronous = (uint)ALL.GL_DEBUG_OUTPUT_SYNCHRONOUS,
		Depth_Clamp = (uint)ALL.GL_DEPTH_CLAMP,
		Depth_Test = (uint)ALL.GL_DEPTH_TEST,
		Dither = (uint)ALL.GL_DITHER,
		Framebuffer_sRGB = (uint)ALL.GL_FRAMEBUFFER_SRGB,
		Line_Smooth = (uint)ALL.GL_LINE_SMOOTH,
		Multisample = (uint)ALL.GL_MULTISAMPLE,
		Polygon_Offset_Fill = (uint)ALL.GL_POLYGON_OFFSET_FILL,
		Polygon_Offset_Line = (uint)ALL.GL_POLYGON_OFFSET_LINE,
		Polygon_Offset_Point = (uint)ALL.GL_POLYGON_OFFSET_POINT,
		Polygon_Smooth = (uint)ALL.GL_POLYGON_SMOOTH,
		Primitive_Restart = (uint)ALL.GL_PRIMITIVE_RESTART,
		Primitive_Restart_Fixed_Index = (uint)ALL.GL_PRIMITIVE_RESTART_FIXED_INDEX,
		Rasterizer_Discard = (uint)ALL.GL_RASTERIZER_DISCARD,
		Sample_Alpha_to_Coverage = (uint)ALL.GL_SAMPLE_ALPHA_TO_COVERAGE,
		Sample_Alpha_to_One = (uint)ALL.GL_SAMPLE_ALPHA_TO_ONE,
		Sample_Coverage = (uint)ALL.GL_SAMPLE_COVERAGE,
		Sample_Shading = (uint)ALL.GL_SAMPLE_SHADING,
		Sample_Mask = (uint)ALL.GL_SAMPLE_MASK,
		Scissor_Test = (uint)ALL.GL_SCISSOR_TEST,
		Stencil_Test = (uint)ALL.GL_STENCIL_TEST,
		Texture_Cube_Map_Seamless = (uint)ALL.GL_TEXTURE_CUBE_MAP_SEAMLESS,
		Program_Point_Size = (uint)ALL.GL_PROGRAM_POINT_SIZE,

	}
}
